### ISSUE TITLE
Target Single Cassandra Node

### ISSUE THREAD

**Issue by BryanSD** [dmchoull/cdeploy#1]
Hi there,

My team at Rackspace is evaluating a few Cassandra schema management tools and would like to look at yours more in-depth. I have three questions/goals in raising this issue:
1. Are you still maintaining this project?
2. If so, we'd like to submit a PR with some improvements. Specifically, it's our understanding that schema changes need to be targeted to an individual Cassandra node since conflicting changes issued to separate nodes in a cluster may result in unpredictable behavior [[0]](http://wiki.apache.org/cassandra/LiveSchemaUpdates#Concurrency) [[1]](http://www.datastax.com/documentation/cassandra/1.2/cassandra/dml/dml_schema_changes_c.html).
3. We may also be interested in making the cdeploy a bit more friendly to use as a library as opposed to a command line utility, although it seems these will be very minor changes the way the code is already structured.

Before we commit to this work we'd like to gather your feedback and ensure you're still willing to maintain the library.

Thanks!

0: http://wiki.apache.org/cassandra/LiveSchemaUpdates#Concurrency
1: http://www.datastax.com/documentation/cassandra/1.2/cassandra/dml/dml_schema_changes_c.html

**Comment by dmchoull** [comment]
Hi Bryan,

I don't have any plans to do anything else with this project, so if you'd like to like to take over and make your changes please feel free to do so. Let me know if there's any way I can be of assistance, though. Hope you can make use of it!

**Comment by BryanSD** [comment]
Great, thanks for the timely response, @dmchoull! Since you no longer wish to maintain the project, would you be willing to add me as an owner on PyPI? My username is bryansd.

**Comment by dmchoull** [comment]
@BryanSD I've added you as an owner

**Comment by BryanSD** [comment]
Thanks, @dmchoull.
